"""add click paid_at and phone fields

Revision ID: 36d9d4ec1d57
Revises: add_seat_visibility_timeout
Create Date: 2026-02-03 07:31:54.578750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36d9d4ec1d57'
down_revision = 'add_seat_visibility_timeout'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topup_transactions', sa.Column('account_phone', sa.String(length=20), nullable=True))
    op.add_column('topup_transactions', sa.Column('raw_prepare_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('topup_transactions', sa.Column('raw_complete_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('topup_transactions', 'amount',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.drop_constraint('uq_topup_merchant_trans_id', 'topup_transactions', type_='unique')
    op.create_index('ix_topup_account_phone', 'topup_transactions', ['account_phone'], unique=False)
    op.drop_column('topup_transactions', 'raw_prepare')
    op.drop_column('topup_transactions', 'raw_complete')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', postgresql.ENUM('male', 'female', 'both', name='gender'), autoincrement=False, nullable=True))
    op.add_column('topup_transactions', sa.Column('raw_complete', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('topup_transactions', sa.Column('raw_prepare', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index('ix_topup_account_phone', table_name='topup_transactions')
    op.create_unique_constraint('uq_topup_merchant_trans_id', 'topup_transactions', ['merchant_trans_id'])
    op.alter_column('topup_transactions', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('topup_transactions', 'raw_complete_payload')
    op.drop_column('topup_transactions', 'raw_prepare_payload')
    op.drop_column('topup_transactions', 'account_phone')
    # ### end Alembic commands ###
