"""add tariff to drivers

Revision ID: 79353b003125
Revises: 20260208_add_tariff
Create Date: 2026-02-15 11:54:19.082252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79353b003125'
down_revision = '20260208_add_tariff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'drivers',
        sa.Column(
            'tariff',
            sa.Enum('standard', 'comfort', 'comfort_plus', 'business', name='tariff'),
            nullable=True,
            server_default='standard',
        )
    )
    op.execute("UPDATE drivers SET tariff = 'standard' WHERE tariff IS NULL")
    op.alter_column('drivers', 'tariff', nullable=False)
    op.create_index(op.f('ix_phone_otps_id'), 'phone_otps', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_index(op.f('ix_phone_otps_id'), table_name='phone_otps')
    op.drop_column('drivers', 'tariff')
    # ### end Alembic commands ###
